<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>260f875b-1a43-4d44-b720-d1051bb299f4</elementGuidId>
   <imagePath>Screenshots/Targets/Page_PeX/span_Login.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.v-btn__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/header/div/div/div/div[2]/div/div/div/a/span</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_PeX/span_Login.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f726c8f0-aa7b-4422-95ed-28d8e4e8295d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn__content</value>
      <webElementGuid>cd49a7d6-c6e4-4b3e-a9ef-4f79feb25f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>f9e33108-5bc2-4a0e-a291-e2cc9910ba8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/header[1]/div[@class=&quot;header py-4&quot;]/div[@class=&quot;container grid-list-lg py-0&quot;]/div[@class=&quot;d-flex align-center  justify-space-between&quot;]/div[@class=&quot;d-flex justify-space-between align-center&quot;]/div[1]/div[@class=&quot;hidden-xs-only mr-4&quot;]/div[@class=&quot;d-flex align-center&quot;]/button[@class=&quot;h6--xsmall text-capitalize mr-4 v-btn v-btn--outlined v-btn--rounded theme--light v-size--default primary--text text--lighten-3&quot;]/span[@class=&quot;v-btn__content&quot;]</value>
      <webElementGuid>1150553c-b28b-4b85-857a-854c6b803287</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/header/div/div/div/div[3]/div/div/div/button/span</value>
      <webElementGuid>36882ab7-b621-43ee-8bf7-c112f6a3aeac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artikel'])[1]/following::span[1]</value>
      <webElementGuid>3291f4d1-366a-44ed-835e-d1603068ad10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelatihan Saya'])[1]/following::span[2]</value>
      <webElementGuid>08825c68-ef2b-41a1-bb42-42bbfe9c3d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/preceding::span[1]</value>
      <webElementGuid>94c2b134-5826-44d1-969c-9140f9617417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dipercaya oleh Beberapa Perusahaan di Indonesia'])[1]/preceding::span[3]</value>
      <webElementGuid>a97b6a19-a487-4636-ab7a-d830b19c7a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>6ffb0868-b174-4b72-9b9c-9c2347678f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>19380e99-b794-4399-911e-dd94cafe9f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>2ffad2bf-1a2d-4fbc-829e-6c07568cfd17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
