<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_error Email belum terdaftar</name>
   <tag></tag>
   <elementGuidId>c5f42580-2ce8-4c90-97ba-19d3dc09efad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-snack__content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'error Email belum terdaftar' or . = 'error Email belum terdaftar')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c4a95a7-f7ee-429d-8a87-53922f8c0577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>85bf5290-1ff7-45fe-a610-364b3c42c0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>c37a9e7e-63de-4b10-a70f-82a0bb77b232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-snack__content</value>
      <webElementGuid>29eb0f4a-df2f-4a18-9462-1f791f75e1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>error Email belum terdaftar</value>
      <webElementGuid>3eb6ce17-c869-4a18-ace3-edd09d942253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/div[1]/div[@class=&quot;v-snack v-snack--active v-snack--has-background v-snack--top&quot;]/div[@class=&quot;v-snack__wrapper v-sheet theme--dark elevation-5 error&quot;]/div[@class=&quot;v-snack__content&quot;]</value>
      <webElementGuid>9e58ec4b-d68c-484c-97af-c976d1a5be2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div</value>
      <webElementGuid>f8e878af-6a97-4756-bf4e-586c8d94c2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Akun Sekarang'])[1]/following::div[6]</value>
      <webElementGuid>6ab44b2c-3105-4359-a085-63de12b798c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/following::div[6]</value>
      <webElementGuid>733d0f33-503c-4299-bd36-0851afded681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[2]</value>
      <webElementGuid>5c979b37-c2f6-4661-9842-3b1cee59288e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div</value>
      <webElementGuid>c6274f3f-2e1a-4973-8c72-4134d88a14f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'error Email belum terdaftar' or . = 'error Email belum terdaftar')]</value>
      <webElementGuid>06c3c222-bfb4-4b59-b2d9-4429a06a6528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
