<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__email</name>
   <tag></tag>
   <elementGuidId>ffbbf674-60d6-4728-bcda-1f7b9e399a77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-226']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a53a60fb-6d4b-4378-af30-0e40a1201aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-20</value>
      <webElementGuid>526eaac0-a21d-42b5-9738-1c41f10fe253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan kata sandi</value>
      <webElementGuid>f12f0487-4187-41f7-9677-d82f8af14107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>20b8d97b-813f-482e-9641-aae52a5c6eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-20&quot;)</value>
      <webElementGuid>8beb0ef4-c0e8-4687-b6b6-293bc228d296</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-20']</value>
      <webElementGuid>81ae55ba-db77-475b-8a6f-9aab5489b6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/section/div/div/div/div/div/div/form/div[2]/div/div/div/div/input</value>
      <webElementGuid>b03e0859-65c0-4de4-95aa-c4a15cda6f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/div/input</value>
      <webElementGuid>bc1f2cf2-5dd5-4f4f-8ba1-384cb46c08e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-20' and @placeholder = 'Masukkan kata sandi' and @type = 'password']</value>
      <webElementGuid>46660aef-4d02-4305-8270-35998318cb4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
