<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__password</name>
   <tag></tag>
   <elementGuidId>d3c9df8c-77ae-4adc-9e94-9dd1290f128e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-16</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'v-text-field__slot' and @placeholder = 'Masukkan kata sandi']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e94c89a-a242-4ca6-94df-6e4191fe8ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-16</value>
      <webElementGuid>8059917e-3baa-4ace-b747-7e40acd57a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c2fcc17-6021-4fc2-943c-3c363c0bfdc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-16&quot;)</value>
      <webElementGuid>bb4da06d-20cc-4050-9b80-554b0c533caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-text-field__slot</value>
      <webElementGuid>7b40ce5c-a1d1-4b4f-b0d3-2db0c3b236ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan kata sandi</value>
      <webElementGuid>6ae116e5-21de-4176-bba3-f4a330cda0a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-16']</value>
      <webElementGuid>89e58132-3be1-4794-ba97-fb036d46f853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/section/div/div/div/div/div/div/form/div/div/div/div/div/input</value>
      <webElementGuid>03f8ddf6-62e7-405a-9a3e-910b84f9411d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a99e2e3f-7196-49c8-a380-b02364e8f491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-16' and @placeholder = 'Masukkan email kamu' and @type = 'text']</value>
      <webElementGuid>a9e24088-8ef3-4ad2-84d5-f22b26773260</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
