<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_namaLengkap</name>
   <tag></tag>
   <elementGuidId>9d566856-8556-4033-9518-b2e07d370d3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-245</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;input-743&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25e594ff-d611-4c13-8178-b0dde3f9ea85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-245</value>
      <webElementGuid>0aed0fc0-f66a-497b-b10b-7bf01102b17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama lengkap kamu</value>
      <webElementGuid>4adb43ac-1589-4113-9bdb-15c7d147f458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2eaebedc-8486-4801-96e7-4c44cd1e0cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-245&quot;)</value>
      <webElementGuid>44116388-d8fa-4d5d-8efb-9de4dead60d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-245']</value>
      <webElementGuid>88feaf49-e5b6-48aa-a917-82650dc085f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/section/div/div/div/div/div[2]/div/form/div/div/div/div/div/input</value>
      <webElementGuid>5d894690-c417-440d-8d57-f9a6fafb6594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cbd038bf-eae8-41a6-bb8c-ec407d164250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-245' and @placeholder = 'Masukkan nama lengkap kamu' and @type = 'text']</value>
      <webElementGuid>967f3dcf-b500-47ce-92de-f5f3d3e91233</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
