<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>e9175e75-6e0c-4070-848d-95bf3e90c7b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-258</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;input-756&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc42d46c-ee7a-4b2a-9b1a-3e0a08e7384b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-258</value>
      <webElementGuid>f9296473-e6cc-42fa-bb5a-54fe5049a24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan email kamu</value>
      <webElementGuid>b2a95df0-77c6-470e-b475-caf0a6732b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>356b2aaa-03ca-4a3a-af9f-0438eaf4bfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-258&quot;)</value>
      <webElementGuid>63b65fab-1a4a-418b-91a5-14ea315513b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-258']</value>
      <webElementGuid>49de67c4-243a-4323-9d86-019d2b9fed4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/section/div/div/div/div/div[2]/div/form/div[6]/div/div/div/div/input</value>
      <webElementGuid>44aae294-3ca5-42d8-9099-158e376c5b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/input</value>
      <webElementGuid>3bf04882-aee3-4ec6-8d1a-a4894c2aa231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-258' and @placeholder = 'Masukkan email kamu' and @type = 'text']</value>
      <webElementGuid>e58f35e3-b7b0-4327-8830-76089413e4de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
