<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>21f186e3-5298-4ae5-8e04-350c45cd68d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-263</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='input-761']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df9e1087-45b6-4e9c-91be-39ce9b3efd06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-263</value>
      <webElementGuid>8a1b38ba-06e3-48cf-8627-fba8d6a6e826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan kata sandi</value>
      <webElementGuid>ad73e9e2-d57b-4a19-861b-1f1da72e12bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f7864f4c-7474-4bcf-a7d5-3d9156b31583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-263&quot;)</value>
      <webElementGuid>dec53c67-af66-40f4-85fd-7bf39308cfe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-263']</value>
      <webElementGuid>ee538941-9c34-404f-b8bc-68e27861b55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/section/div/div/div/div/div[2]/div/form/div[7]/div/div/div/div/div/div/input</value>
      <webElementGuid>6c66fbcd-2eda-476a-9379-2e79c0548bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div/input</value>
      <webElementGuid>69b0f393-1243-437c-ae15-268afb96e1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-263' and @placeholder = 'Masukkan kata sandi' and @type = 'password']</value>
      <webElementGuid>2db22a45-7d68-4e36-b6cb-9d9ac1007782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
