<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_noHP</name>
   <tag></tag>
   <elementGuidId>6ca12b35-5f99-4e12-878a-96885db37f66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-254</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;input-752&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>105c51d2-d8f2-4bbe-ae71-e8b42cb2c513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-254</value>
      <webElementGuid>ba64c1f8-d45b-483e-95ea-35fcd34cb1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan nomor handphone</value>
      <webElementGuid>4f6026ae-561d-4d9d-b4ec-7de5e85ec70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f74b373b-c420-4d03-94c8-d4c2c651a93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-254&quot;)</value>
      <webElementGuid>e9ce04d9-4e18-40bc-b93a-0229df791bbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-254']</value>
      <webElementGuid>b4a092b8-6648-4431-bc14-6c719c51275e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/section/div/div/div/div/div[2]/div/form/div[4]/div/div/div/div/input</value>
      <webElementGuid>811d8f51-7616-4894-8fbb-c6163601c1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>80f69913-44a8-420f-bf3a-0f1eef0af37a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-254' and @placeholder = 'Masukan nomor handphone' and @type = 'text']</value>
      <webElementGuid>617e4a14-5c99-4c7a-8c57-df43eee7fcd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
