<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>panah_DropDown</name>
   <tag></tag>
   <elementGuidId>a774fcb7-b737-436d-a537-b9a0ebd14b1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div/main/div/section/div[1]/div/div[1]/div/div[2]/div/form/div[3]/div/div/div/div[1]/div[2]/div/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
