<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyDetailCourse_Ringkasan</name>
   <tag></tag>
   <elementGuidId>9cbcb2de-c1b3-4141-8239-3cae6cc0f466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-tab.v-tab--active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div[2]/div/div/div/div/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6071baa8-1f98-4a3a-9bac-ab3b0ec2f360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99fb3092-98c8-49c0-a63e-2e1367b808a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6fa21f99-101c-44f1-abbc-a49ef85ad630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>90115b0a-7f60-47ff-be6c-6b6369471f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-tab v-tab--active</value>
      <webElementGuid>def361d5-bbe6-49fe-9c42-221d05baa873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              Ringkasan
              </value>
      <webElementGuid>6cf18624-564a-42b4-afc6-854d1ace12eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;course__detail&quot;]/div[@class=&quot;container py-6&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-7 col-12&quot;]/div[@class=&quot;v-tabs course__detail__tab mb-7 theme--light&quot;]/div[@class=&quot;v-item-group theme--light v-slide-group v-tabs-bar v-tabs-bar--is-mobile primary--text transparent&quot;]/div[@class=&quot;v-slide-group__wrapper&quot;]/div[@class=&quot;v-slide-group__content v-tabs-bar__content&quot;]/div[@class=&quot;v-tab v-tab--active&quot;]</value>
      <webElementGuid>84e884c2-2781-4dab-ac0d-c8a14f7cb389</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div[2]/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>26268b2a-5ec8-487d-8334-49782c549d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='managing self - hybrid learning'])[1]/following::div[45]</value>
      <webElementGuid>7930d844-9b76-41ff-acee-ed22770b07d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artikel'])[1]/following::div[67]</value>
      <webElementGuid>240c970d-4228-47f6-bf96-aa96758fa4b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanya Jawab'])[1]/preceding::div[1]</value>
      <webElementGuid>9f1fc4d6-18c8-4ef9-8b05-9121d453c437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>79e05e40-cd2a-43da-8082-d3d51c59e6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
              Ringkasan
              ' or . = '
              Ringkasan
              ')]</value>
      <webElementGuid>75485604-584a-485c-bffb-7fad928a2a7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
