<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ListAtas_dropdownSearch</name>
   <tag></tag>
   <elementGuidId>f770b585-b5ad-44c9-ae93-10c29a223f63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list-item-668</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;list-item-2786&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b505aec6-a1cd-44dd-95b7-a80b1c53b4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d8e084bc-8e15-4310-969f-c11993d5f378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list-item-668</value>
      <webElementGuid>52324fa1-5567-4093-b79c-efe66d59dcc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pa-0 v-list-item theme--light</value>
      <webElementGuid>aa39d8aa-d67c-4a90-b25f-b1af4941822a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                      CLASSROOM
                     Managing Self - Hybrid Learning</value>
      <webElementGuid>d3ccc933-45d6-42fc-a159-df857d61e131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-668&quot;)</value>
      <webElementGuid>411b80fd-45f6-4e07-bd2c-0e66e27c1ad0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='list-item-668']</value>
      <webElementGuid>cffbd999-00f8-4df1-bf0c-25810d9ab4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-664-0']/div/div</value>
      <webElementGuid>c55f9339-4407-40ff-aeb2-cd0353379026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1) ulasan'])[8]/following::div[7]</value>
      <webElementGuid>2b6ffa46-04a0-447c-9c44-0dff9304011a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='self learning'])[16]/following::div[13]</value>
      <webElementGuid>51a7fa15-439b-4c5e-9d55-1d42f935d4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[8]</value>
      <webElementGuid>c7dc8cb4-460e-4b72-a9db-5c91b7724f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[8]</value>
      <webElementGuid>1ce28113-0dab-4695-8b29-138702fa6481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>67eddf0b-d0ce-442e-a6cc-23cc3c752de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'list-item-668' and (text() = ' 
                      CLASSROOM
                     Managing Self - Hybrid Learning' or . = ' 
                      CLASSROOM
                     Managing Self - Hybrid Learning')]</value>
      <webElementGuid>336093ca-eda4-47d6-8cd7-2fe662f29e24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
