<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TextField_Search</name>
   <tag></tag>
   <elementGuidId>99fe9875-2858-447f-aba0-2b38f0be2c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-246</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-246']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30b67675-47fc-4668-b279-909281363456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-246</value>
      <webElementGuid>205e2ece-088f-474b-beae-a8ea470c00da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44be7ae1-d35d-4ce9-92c3-a45ccacec1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ef487199-de9b-4b2a-ad9c-42bb792c752c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-246&quot;)</value>
      <webElementGuid>eb7a35f7-aa1f-4a24-af1f-728aa5376595</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-246']</value>
      <webElementGuid>379b6c6f-942e-4b9c-889a-8ab7b48dffdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/header/div/div/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>b5498a8f-d17d-440e-a06f-a3b3e1311f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>049d2c03-2e73-4d43-9aa3-17dcc19a6f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-246' and @type = 'text']</value>
      <webElementGuid>c860f64f-41b1-4d36-b97b-19047150571d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
