<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_ValidLogin</name>
   <tag></tag>
   <elementGuidId>e568db09-2463-4752-92c9-b792f202725e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.h3--large.mb-1.text-capitalize</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div/div/div/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>45206f20-8711-45e8-8ddf-6b5c37004997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h3--large mb-1 text-capitalize</value>
      <webElementGuid>a2ed8ddf-1b8a-4247-9c27-ba7ef00370f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hai Rudy S</value>
      <webElementGuid>38a04f52-6508-4dc8-b97a-43c0eeecd15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container grid-list-lg py-0&quot;]/div[1]/div[@class=&quot;banner white--text&quot;]/p[@class=&quot;h3--large mb-1 text-capitalize&quot;]</value>
      <webElementGuid>b9da158d-a3aa-4073-9417-d15ba112dde6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/p</value>
      <webElementGuid>4d411d60-745e-4d36-9187-0c2246212a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artikel'])[1]/following::p[1]</value>
      <webElementGuid>d698c2a1-40a7-4412-83cb-787a5d2de60c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelatihan Saya'])[1]/following::p[1]</value>
      <webElementGuid>3ae88839-c70c-42d7-aef7-69e3a7b02b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::p[2]</value>
      <webElementGuid>69b5a0e8-746a-484d-b045-4737d17c65d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='self learning'])[1]/preceding::p[2]</value>
      <webElementGuid>8cb48597-e988-4306-9765-83f17326207c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hai Rudy S']/parent::*</value>
      <webElementGuid>c066999a-42a1-45b4-984e-d1098d7d85fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/p</value>
      <webElementGuid>2f3d139b-4840-4716-998b-102aa8fad9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Hai Rudy S' or . = 'Hai Rudy S')]</value>
      <webElementGuid>edd8ef7c-de8b-47e7-99b4-85ecaef03655</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
